# Appointments Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
  namespace: medical-record
  labels:
    app: appointments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: docker.io/naksito03/appointments:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9092
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: APPOINTMENTS_PORT
            value: "9092"
          - name: USERS_PORT
            value: "9090"
          - name: USERS_HOST
            value: "users-service"
          - name: DB_URL
            value: "jdbc:postgresql://postgres:5432/appointments"
          - name: DB_USERNAME
            value: "admin"
          - name: DB_PASSWORD
            value: "admin"
        livenessProbe:
          grpc:
            port: 9092
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 9092
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
        - name: regcred

---

# Users Service
apiVersion: v1
kind: Service
metadata:
  name: appointments
  namespace: medical-record
spec:
  selector:
    app: appointments
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP
